Add WEIGHTS_JSON file as cli option
tnicola/cypress-parallel pull request #109
Opened 2022-06-03 18:59 UTC by jayc13

2022-06-11 14:08 UTC, tnicola commented on package.json
> +  "version": "0.10.0",
This is just the demo package, there's no need to change the version

2022-06-11 14:09 UTC, tnicola requested changes
Hi Jay, thanks for this pull request, I've added a minor comment. Could you also please update the doc?

2022-06-11 14:39 UTC, jayc13 commented
> Hi Jay, thanks for this pull request, I've added a minor comment. Could you also please update the doc?

Documentation updated! Ready to go 🚀

2022-06-13 20:34 UTC, tnicola approved these changes

2022-06-13 21:04 UTC, jayc13 commented
<img width="639" alt="Screen Shot 2022-06-13 at 6 03 38 PM" src="https://user-images.githubusercontent.com/2935783/173445079-32e08f13-f518-4bde-b182-ce97cbe402db.png">
@tnicola  I can't merge it

2022-06-13 21:23 UTC, merged

2022-06-13 21:23 UTC, tnicola commented
@jayc13 merged!Thanks for your contribution! :)