feat: add mono-repo support via reporterModulePath option
tnicola/cypress-parallel pull request #81
Opened 2022-01-24 11:50 UTC by joshuajtward

2022-01-25 14:31 UTC, tnicola commented
Hi @joshuajtward , I think this is a good idea!Could you please change the argument alias?Since it conflicts with the "strictMode" one. Also, if you could update the doc in the README file that would be great too!Thanks!

2022-01-25 14:32 UTC, tnicola requested changes

2022-01-25 14:32 UTC, tnicola commented on lib/settings.js
> +  .option('reporterModulePath', {
Change the alias please

2022-01-26 11:47 UTC, joshuajtward commented
Thank @tnicola, updated to use `n` instead and added some info in the README. I hadn't noticed `strictMode` in the latest version 🤦

2022-01-28 10:45 UTC, tnicola approved these changes

2022-01-28 10:46 UTC, merged